
set nocompatible
filetype off                 

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'kien/ctrlp.vim'
Bundle 'jnwhiteh/vim-golang'
Bundle 'yko/mojo.vim' 
Bundle 'Lokaltog/vim-powerline'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/syntastic'
Bundle 'majutsushi/tagbar'
Bundle 'Valloric/YouCompleteMe'
Bundle 'nvie/vim-flake8'
Bundle 'jelera/vim-gummybears-colorscheme'

let mapleader = "," 

filetype plugin indent on

set wildmenu 
set ttyfast " Optimize for fast terminal connections
set gdefault " Add the g flag to search/replace by default
set encoding=utf-8 
set nobomb
set binary " No empty newlines at the end of files
set backspace=indent,eol,start " Enable backspace in VIm
set noswapfile
set nobackup
set nowritebackup

set number
syntax on
syntax enable
set cursorline
set tabstop=4

set hlsearch
set ignorecase
set incsearch
set laststatus=2

set mouse=a
set visualbell

set nostartofline
set ruler
set showmode

set title
set showcmd

nnoremap ; :

" Solarized colorscheme for Vim
let g:solarized_termtrans = 1
let g:solarized_termcolors=256
colorscheme solarized
set background=dark

set showmatch
set autoindent
set wildignore=*.swp,*.bak,*.pyc,*.class
set smarttab
set noexrc 
set shiftwidth=4
set wrap 
set showbreak=↪ 
set clipboard=unnamed

" ---------------TagBar ---------------
let g:tagbar_ctags_bin='/usr/local/bin/ctags'	" Proper ctags locations
let g:tagbar_width=35	" Width of the tagbar pane

" --------------- PowerLine ---------------
let g:Powerline_symbols = 'fancy'
let g:Powerline_stl_path_style = 'short'
call Pl#Theme#InsertSegment('ws_marker', 'after', 'lineinfo')

" --------------- Python ---------------
" python-mode
" let g:pymode_folding = 0 "Disable python folding
" let g:pymode_lint_signs = 1 "Place error signs
" let g:pymode_virtualenv = 1 "Auto fix vim python paths if virtualenv enabled
autocmd BufWritePost *.py call Flake8()

" --------------- Go-lang ---------------
set rtp+=$GOROOT/misc/vim

" --------------- Haskell ---------------
au Bufenter *.hs compiler ghc 					" Use GHC functionality for Haskell files
let g:haddock_browser = "open"					" Configure browser for haskell_doc.vim
let g:haddock_browser_callformat = "%s %s"

" --------------- Startup items ---------------
autocmd VimEnter * NERDTree
autocmd BufEnter * NERDTreeMirror

autocmd VimEnter * wincmd w
