set nocompatible
filetype off

" Vundle for plugin management 
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'mileszs/ack.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'Lokaltog/vim-easymotion'
" Bundle 'amirh/HTML-AutoCloseTag'
" Bundle 'JuliaLang/julia-vim'
" Bundle 'yko/mojo.vim' 
" Bundle 'mtth/locate.vim'
" Bundle 'lsdr/monokai'
Bundle 'tomasr/molokai'
" Bundle 'Shougo/neocomplcache'
Bundle 'Shougo/neocomplete.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'myusuf3/numbers.vim'
Bundle 'vim-scripts/perl-support.vim'
Bundle 'scrooloose/syntastic'
Bundle 'godlygeek/tabular'
Bundle 'majutsushi/tagbar'
Bundle 'tomtom/tcomment_vim'
Bundle 'bling/vim-airline'
" Bundle 'bling/vim-bufferline'
Bundle 'vim-scripts/VimClojure'
" Bundle 'altercation/vim-colors-solarized'
Bundle 'moznion/vim-cpanfile'
Bundle 'tpope/vim-fugitive'
Bundle 'airblade/vim-gitgutter'
Bundle 'jnwhiteh/vim-golang'
" Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-markdown'
Bundle 'terryma/vim-multiple-cursors'
" Bundle 'tpope/vim-rails'
" Bundle 'vim-ruby/vim-ruby'
Bundle 'mhinz/vim-startify'
Bundle 'tpope/vim-surround'
Bundle 'gmarik/vundle'

let mapleader = "," "
nnoremap ; :

filetype plugin indent on " Filetype detection and indentation is on
syntax on                 " Enable syntax highlighting
syntax enable             "
set mouse=a               " Enable mouse in all modes

set wildmenu                   " Better command-line completion
set ttyfast                    " Optimize for fast terminal connections
set gdefault                   " Add the g flag to search/replace by default
set encoding=utf-8             "
set binary                     " No empty newlines at the end of files
set backspace=indent,eol,start " Enable backspace in VIm
set noswapfile                 "
set nobackup                   "
set nowritebackup              "

" Backups and swapfiles
set backupdir=$HOME/.vim/tmp
set directory=$HOME/.vim/tmp

" Visual
set number         " Enable line numbers
set cursorline     " Highlight current line
set laststatus=2   " Always show status line
set tabstop=4      " Make tabs as wide as four spaces
set nobomb         "
" set noerrorbells   " Disable error bells
set visualbell     " Enable visual bell
set nostartofline  " Don’t reset cursor to start of line when moving around.
set ruler          " Show the cursor position
set showmode       " Show the current mode
set title          " Show the filename in the window titlebar
set showcmd        " Show the (partial) command as it’s being typed

" Searching
set hlsearch   " Highlight searches
set ignorecase " Ignore case of searches
set incsearch  " Highlight dynamically as pattern is typed

" Code folding
set foldmethod=indent " Fold based on indent
set foldnestmax=10    " Deepest fold is 10 levels
set nofoldenable      " Don't fold by default
set foldlevel=1         

" Colorscheme for Vim
" let g:solarized_termtrans  = 1
" let g:solarized_termcolors = 16
set background=dark
" colorscheme solarized
colorscheme molokai 
let g:molokai_original = 1
let g:rehash256 = 1

set showmatch
set autoindent
set wildignore=*.swp,*.bak,*.pyc,*.class
set smarttab
set noexrc 
set shiftwidth=4

set wrap        " Wrap text
set showbreak=↪ " Better line break display

" Use system clipboard
set clipboard=unnamed

autocmd FileType gitcommit setlocal spell " Spellcheck in git-commit

au BufNewFile,BufRead *.psgi set filetype=perl
au BufNewFile,BufRead cpanfile set filetype=cpanfile
au BufNewFile,BufRead cpanfile set syntax=perl.cpanfile

let g:LargeFile=100 " Load files upto 50mb without creating *.swp

" --------------- syntastic ---------------
let g:syntastic_python_flake8_args = '--ignore=W191,E501,E121,E122,E123,E128'

 " --------------- ctrlp ---------------
let g:ctrlp_custom_ignore       = '\v[\/](local|nytprof|blib)$' " Ignore local folder from ctrlp
let g:ctrlp_by_filename         = 0                             " Search by filename
let g:ctrlp_match_window_bottom = 1                             " Display window at the top
let g:ctrlp_open_new_file       = 't'                           " Open new file in a tab

" --------------- neocomplcache ---------------
" let g:neocomplcache_enable_at_startup = 1            " Enable at startup
" let g:neocomplcache_enable_smart_case = 1            " Use smartcase.
" let g:neocomplcache_enable_camel_case_completion = 1 " Use cameL case completion.
" let g:neocomplcache_min_syntax_length = 3            " Sets minimum char length of syntax keyword.
" let g:neocomplcache_dictionary_filetype_lists = {
"   	\ 'cpanfile' : $HOME . '/.vim/bundle/vim-cpanfile/dict/cpanfile.dict'
"   	\ }

" --------------- neocomplete ---------------
let g:acp_enableAtStartup                           = 1
let g:neocomplete#enable_at_startup                 = 1
let g:neocomplete#enable_smart_case                 = 1 " Use smartcase.
let g:neocomplete#sources#syntax#min_keyword_length = 3 " Set minimum syntax keyword length.
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete

" --------------- startify ---------------
let g:startify_custom_header =
	\ map(split(system('cowsay'), '\n'), '"   ". v:val') + ['','']

" ---------------TagBar ---------------
let g:tagbar_ctags_bin = '/usr/local/bin/ctags' " Proper ctags locations
let g:tagbar_width     = 35                     " Width of the tagbar pane

" --------------- Airline ---------------
let g:airline_theme             = 'murmur'
let g:airline_left_sep          = '⮀'
let g:airline_right_sep         = '⮂'
let g:airline_branch_prefix     = '⭠'
let g:airline_readonly_symbol   = '⭤'
let g:airline_linecolumn_prefix = '⭡'

" --------------- NERDTree ---------------
let NERDTreeIgnore    = ['\.pyc$'] " Ignore these files in NERDTree
let g:NERDTreeWinSize = 40
map <C-t> :NERDTreeToggle<CR>

" --------------- Startup items ---------------
" autocmd VimEnter * NERDTree
" autocmd BufEnter * NERDTreeMirror

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" --------------- Javascript ---------------
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1  = "inc"

" --------------- Go-lang ---------------
set rtp+=$GOROOT/misc/vim

" --------------- Haskell ---------------
" Configure browser for haskell_doc.vim
let g:haddock_browser            = "open"
au Bufenter *.hs compiler ghc 					" Use GHC functionality for Haskell files
let g:haddock_browser = "open"					" Configure browser for haskell_doc.vim
let g:haddock_browser_callformat = "%s %s"

" --------------- Exit items ---------------
autocmd VimEnter * wincmd w
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
